version: "3.9"

services:
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - db
      - redis
  worker:
    build:
      context: ../worker
      dockerfile: Dockerfile
    env_file:
      - ../.env
    depends_on:
      - redis
      - db
  db:
    image: postgis/postgis:15-3.3
    restart: unless-stopped
    environment:
      POSTGRES_USER: beachhub
      POSTGRES_PASSWORD: beachhub
      POSTGRES_DB: beachhub
    ports:
      - "5432:5432"
  redis:
    image: redis:7.2
    restart: unless-stopped
    ports:
      - "6379:6379"
  web:
    build:
      context: ../web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ../.env
    depends_on:
      - api
